### ISSUE TITLE
bootstrap.sh: Add postgres user and db

### ISSUE THREAD

**Issue by aboutaaron** [cirlabs/vm#11]

**Comment by mikejcorey** [comment]
The only thing we did wrong yesterday was to use CREATE ROLE instead of CREATE USER.

So, one way to do it programmatically:

```bash
sudo su - postgres
"CREATE USER nicar SUPERUSER;" | psql -d postgres
exit
```

**Comment by aboutaaron** [comment]
:thumbsup:

—

**Comment by aboutaaron** [comment]
This should go into the "after" steps the user must do after the bootstrap runs
