### ISSUE TITLE
Add gephi?

### ISSUE THREAD

**Issue by mikejcorey** [cirlabs/vm#36]

**Comment by esagara** [comment]
Currently the process looks like this:
```bash
#download
wget https://github.com/gephi/gephi/releases/download/v0.9.1/gephi-0.9.1-linux.tar.gz

#unzip
tar -xvzf gephi-0.9.1-linux.tar.gz

#Gephi has no application shortcut with this install process, we would probably 
#have to build one so people did not have to launch from command line. 
#The environment variable  is a workaround for a fatal libEGL error that prevents
#the software from running. Currently the process to run is as follows:
cd gephi-0.9.1
LIBGL_ALWAYS_SOFTWARE=1 ./bin/gephi
```
Alternatively we can install with ```apt-get``` but that would be a nightly build and not the stable build.

**Comment by mikejcorey** [comment]
Sounds like this is a mess, let's kill it.

**Comment by esagara** [comment]
Ok so no good suggestions for how to proceed with installing Gephi. I checked out the gephi-daily ppa and the actual packages have not been updated since 2012. The decision is not to support a Gephi install at this time.
