### ISSUE TITLE
Check for prompts when Bootstrap.sh is run

### ISSUE THREAD

**Issue by esagara** [cirlabs/vm#48]
We should keep an eye on whether or not we need to pass the ```-y``` flag to any ```apt-get install``` commands.

**Comment by esagara** [comment]
Q-GIS has a prompt. But that asks the question do we really want to remove them? People running bootstrap.sh may want to have the option to decline...

**Comment by mikejcorey** [comment]
QGIS has a prompt? Is this because of key issues?
