### ISSUE TITLE
Supplemental blog post on how to install Guest Additions, add shared folders

### ISSUE THREAD

**Issue by mikejcorey** [cirlabs/vm#59]

**Comment by mikejcorey** [comment]
Running shell script that's included on the Guest Additions CD (which automatically mounts if you try to do it under Devices in VirtualBox) works on Mac. Has anyone tested it in Windows?

**Comment by mikejcorey** [comment]
Same (shell script) worked on Windows as well.

**Comment by mikejcorey** [comment]
Shared folders also worked on both Windows and Mac host machines.

**Comment by esagara** [comment]
Ok process for installing Guest Additions and getting the resolution issue fixed:

1. Make sure you have the guest additions iso.
2. Launch the VM. Before logging in go to Devices>Insert Guest Additions CD image
3. Log into the VM.
4. Open the terminal and enter the following command: ```sudo /media/nicar/VBOXADDITIONS_5.1.14_112924/VBoxLinuxAdditions.run```
5. Enter password when prompted and allow it to run.
6. Restart XUbuntu

**Comment by mikejcorey** [comment]
OK, well this at least used to work on Windows, per above. This is the procedure outlined in slides 44-52. Closing this for now.

https://docs.google.com/presentation/d/1asY7pR76_dArQhnInRV3dAZyP39UvLXGi9SP0ewFQYM/edit#slide=id.p
