### ISSUE TITLE
2018 vm changes

### ISSUE THREAD

**Issue by mikejcorey** [cirlabs/vm#71]
Switch from ipython to jupyter
kill zshell
switch from virtualenvwrapper to pyenv
add pyenv
set up pyenv virtualenvs
sample virtualenvs
put django version at 1.x
add sqlite
remove atom
what's up with tabula
set up altair for jupyter
add R, R studio
pyscopg2
conda

**Comment by esagara** [comment]
- [ ] Switch from ipython to jupyter
- [ ] kill zshell
- [ ] switch from virtualenvwrapper to pyenv
- [ ] add pyenv
- [ ] set up pyenv virtualenvs
- [ ] sample virtualenvs
- [ ] put django version at 1.x
- [ ] add sqlite
- [ ] remove atom
- [ ] what's up with tabula
- [ ] set up altair for jupyter
- [ ] add R, R studio
- [ ] pyscopg2
- [ ] conda

**Comment by aboutaaron** [comment]
These are great changes! (zsh is still the shit, though.)

**Comment by esagara** [comment]
Dropped tabula, conda and R studio from the install process. Closing this issue.
