### ISSUE TITLE
Upgrade to Xubuntu 18.04

### ISSUE THREAD

**Issue by mikejcorey** [cirlabs/vm#76]

**Comment by meli-lewis** [comment]
Leaving a note for myself as much as for anyone here -- I can run Xubuntu from a USB drive using [these directions](https://help.ubuntu.com/community/Installation/FromUSBStick), but got the following error at first: `This kernel requires the following feature not present on the CPU: pae`.

I tried to enable pae from the VirtualBox interface per [this StackExchange Q](https://askubuntu.com/questions/163550/virtualbox-install-12-04-guest-pae-not-present?newreg=1d759048623a4ca991d6a5c982a41dae), but could not. However, the command line tip worked: `VBoxManage modifyvm <VM_name> --pae on`.
