### ISSUE TITLE
Did you install the extension pack? If so we might need to undo for copyright reasons

### ISSUE THREAD

**Issue by mikejcorey** [cirlabs/vm#81]

**Comment by meli-lewis** [comment]
Looks like I did:

```
$ VBoxManage list extpacks
Extension Packs: 1
Pack no. 0:   Oracle VM VirtualBox Extension Pack
Version:      6.0.4
Revision:     128413
Edition:      
Description:  USB 2.0 and USB 3.0 Host Controller, Host Webcam, VirtualBox RDP, PXE ROM, Disk Encryption, NVMe.
VRDE Module:  VBoxVRDP
Usable:       true 
Why unusable: 
```

After I uninstall, should I export the VMDK again?

**Comment by mikejcorey** [comment]
Yes, please. I think with the recent changes we have a solid test build I
can shop around today.

**Comment by meli-lewis** [comment]
Is this an issue? I don't know enough about this product to tell! https://github.com/cirlabs/vm/blob/master/install-vm.sh#L99

**Comment by meli-lewis** [comment]
Does this mean I'll need to build from scratch?

<img width="398" alt="screen shot 2019-02-26 at 9 09 31 am" src="https://user-images.githubusercontent.com/2907073/53423123-61392480-39a6-11e9-9079-ad28136d65c7.png">

Result Code: | NS_ERROR_FAILURE (0x80004005)
-- | --
Component: | ConsoleWrap
Interface: | IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

**Comment by mikejcorey** [comment]
I think you can just disable USB 2.0 for now, but i don't know if we can
avoid that message by re-creating.

**Comment by mikejcorey** [comment]
Maybe if you disable USB 2.0 and then restart it will be fine.

**Comment by meli-lewis** [comment]
I did so and it was fine!
