### ISSUE TITLE
Can VirtualBox 6.0 run on Windows 7?

### ISSUE THREAD

**Issue by mikejcorey** [cirlabs/vm#89]

**Comment by nlierly** [comment]
Windows 7 is now unsupported by MS - however I wouldn't be surprised if we see a machine with it show up.

1.4 Supported Host Operating Systems
Currently, Oracle VM VirtualBox runs on the following host OSes:
• Windows hosts (64-bit):
– Windows 7
– Windows 8
– Windows 8.1
– Windows 10 RTM (1507) build 10240
– Windows 10 November Update (1511) build 10586
– Windows 10 Anniversary Update (1607) build 14393
– Windows 10 Creators Update (1703) build 15063
– Windows 10 Fall Creators Update (1709) build 16299
– Windows 10 April 2018 Update (1803) build 17134
– Windows 10 October 2018 Update (1809) build 17763
– Windows Server 2008 R2
– Windows Server 2012
– Windows Server 2012 R2
– Windows Server 2016
– Windows Server 2019

-per https://download.virtualbox.org/virtualbox/6.0.16/UserManual.pdf
